### ISSUE TITLE
Use mt as a library (thumbnailer)

### ISSUE THREAD

**Issue by prologic** [prologic/tube#16]
This reduces the no. of external binaries we depend on.

Depends on: mutschler/mt#18

**Comment by prologic** [comment]
This is still planend. I just don't have much bandwidth of late due to work. I would enocurage the community to put up PRs to help push this project along. Thank you!

**Comment by mutschler** [comment]
@prologic so i got some time to start with the whole library thing... from what i see you only use `mt` to create a single non-blank screenshot of the file.

If that's the case i'd recommend you stick to the binary file (or use ffmpeg if you want to get rid of `mt`). Mainly because if you'll depend on `mt` you'll need to enable CGO, compile ffmpeg and (statically) link it to the compiled ffmpeg version... That seems like a lot of trouble for "just creating a single screenshot"

**Comment by prologic** [comment]
Thanks for the update!
