### ISSUE TITLE
MT invalid option on debian 

### ISSUE THREAD

**Issue by Bugz000** [prologic/tube#33]
```
ERRO[0031] error generating thumbnail: cmd.CombinedOutput error: exit status 1
mt: invalid option -- 'b'
Try 'mt --help' or 'mt --usage' for more information. 
```

i also see an issue opened regarding disbling the Upload feature, i would also like this feature, the majority of folk running this are wanting to share their own videos - not become the next "imgur" for videos... but i can't even get it working, install directions need an overhaul, once working i will see about binding UPLOAD to a specific or local addresses only - and perhaps issuing a better worded install guide as from what i gather, english is not the native language of any member of the dev team and it is confusing

a more granular encoding option would be great also - or to keep the original file and only encode lower resolutions as i already export optimised files, i just need a super simple distribution platform... 

i am happy to collaborate on this - but i need you to help me, before i can help you

**Comment by prologic** [comment]
> from what i gather, english is not the native language of any member of the dev team and it is confusing

That was a pretty blatant assumption on your part 🤣 - English is my native language! Anyway...

Regardless I do agree, the README could be cleaned up and installation instructions made better.

For some context/background (_because it's not documented_):

- I built this in a single weekend for my wife so she could upload, process and then re-share/download/whatever videos for real estate rental walkthroughs without having to learn Handbrake and go knows what else, but also to be self-hosted where we know where the date is (_on my servers at home_).
- The lower resolution resolution was done to satisfy the needs of folks like my old man who often have poor internet connectivity and/or who don't pay for a lot of "traffic" and can't afford to waste multi-MB high-res videos.

Otherwise yes we can certainly make some of these things more configurable and I don't have a problem with putting the upload facilities behind a private network/address or behind some simple auth.

Let's break this out though into separate things we can do in smaller chunks, I don't like issues that cover too many things as it becomes hard to track and it's "too much to do" sort of thing.

Thanks for your interest in the project!

**Comment by Bugz000** [comment]
ah my mistake, i could have sworn i saw something relating to native language in another issue, but i could have been mixing this with the issues on the original project this was forked from? i'm not sure...

i have been working on this in my spare time already, but in an alternative direction;
i have been simplifying the process significantly and been compressing dependencies and functionality into a single file, i have a live preview you can view here, this is performed all within one php file with one favicon file and 4 colors for the icons (i plan to recreate the icons entirely in CSS so they can be dynamically colored also), dependencies only with HTML5, CSS, PHP, and JS, and ofcourse url rewrite in lighttpd

[live preview](https://bugz000.co.uk/v/face%20first!%20-%20FPV%20freestyle)

i have also been working on a method to generate thumbnails dynamically though this did not work out so well - this page is more akin to the original project, and has all the functionality of that already, so the next thing would be adding possible transcoding and thumbnails, and ofcourse an upload page

i do apologise i am not well versed in how github works so i'm not sure how else to keep you updated on this progress, perhaps would a fork be appropriate? i'm not sure... i am a very basic github user so any advice would be great

either way i'm excited with how well this works already, so please do let me know what you would like to do from this point forward :) 
thankyou!

**Comment by prologic** [comment]
Yeah what you've doing is probably not compatible with my project at the code level so it would not be possible to merge your work.

I'd recommend you just create a new project. Since you're not deriving from my source code (_or where I originally forked from_) you're very likely (_but this is not legal advice_) to license your work however you see fit.

It _might_ be nice to link back to my project as "source of inspiration" maybe :)

**Comment by Bugz000** [comment]
ah perfect, i shall release as a new project once this is all completed then <3 and i thankyou for taking the time to discuss this 

> It _might_ be nice to link back to my project as "source of inspiration" maybe :)

it would be outrageous not to! <3
